### ISSUE TITLE
Server.py:  wsgiref installing error.

### ISSUE THREAD

**Issue by yakushevichsv** [twilio/voice-quickstart-server-python#16]
I tried to deploy the server code locally and on heroku.
python v 3.5
pip3 install -r requirements.txt
I am getting the following error:

Collecting wsgiref==0.1.2 (from -r /tmp/build_ef8df6ccab0007ab774d10ed7abeb19a/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 9))
         Downloading wsgiref-0.1.2.zip
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-a03u3qz9/wsgiref/setup.py", line 5, in <module>
               import ez_setup
             File "/tmp/pip-build-a03u3qz9/wsgiref/ez_setup/__init__.py", line 170

**Comment by bchen-twilio** [comment]
Hi @yakushevichsv 

Thanks for choosing the Twilio SDK.

To get rid of the error you can simply remove the `wsgiref` line in `requirements.txt` and try again. The library is actually already built-in in python3 but is still a requirement for python2 compatibility.

Let me know if this helps.

-bobie

**Comment by sryze** [comment]
@bchen-twilio I had the same error as in the first post, and after removing `wsgiref` from requirements there was another issue:

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\werkzeug\serving.py", line 53, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 66, in <module>
    app.run(host='0.0.0.0', port=port, debug=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 758, in run
    from werkzeug.serving import run_simple
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\werkzeug\serving.py", line 56, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'
```

Changing `Werkzeug` version to ` 0.11.15` (as suggested [here](https://stackoverflow.com/questions/39214395/running-flask-dev-server-in-python-3-6-raises-importerror-for-socketserver-and-f)) fixed it. I'm using Python 3.6.1 on Windows.

**Comment by bchen-twilio** [comment]
Closing this issue assuming the `runtime.txt` fixed the deployment issue.
