### ISSUE TITLE
Heroku Build Fails

### ISSUE THREAD

**Issue by Jbithell** [twilio/voice-quickstart-server-python#9]
Heroku build fails, with message
```
-----> Python app detected
-----> Installing python-2.7.13
-----> Installing pip
-----> Installing requirements with pip
       Collecting Flask==0.10.1 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 1))
         Downloading Flask-0.10.1.tar.gz (544kB)
       Collecting Jinja2==2.7.3 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 2))
         Downloading Jinja2-2.7.3.tar.gz (378kB)
       Collecting MarkupSafe==0.23 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 3))
         Downloading MarkupSafe-0.23.tar.gz
       Collecting Werkzeug==0.9.6 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 4))
         Downloading Werkzeug-0.9.6.tar.gz (1.1MB)
       Collecting httplib2==0.9 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 5))
         Downloading httplib2-0.9.zip (209kB)
       Collecting itsdangerous==0.24 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 6))
         Downloading itsdangerous-0.24.tar.gz (46kB)
       Collecting six==1.8.0 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 7))
         Downloading six-1.8.0-py2.py3-none-any.whl
       Collecting twilio==6.0rc11 (from -r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 8))
         Downloading twilio-6.0.0rc11-py2.py3-none-any.whl (694kB)
       Collecting pytz (from twilio==6.0rc11->-r /tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/requirements.txt (line 8))
         Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
       Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, httplib2, six, pytz, twilio
         Running setup.py install for Werkzeug: started
           Running setup.py install for Werkzeug: finished with status 'done'
         Running setup.py install for MarkupSafe: started
           Running setup.py install for MarkupSafe: finished with status 'done'
         Running setup.py install for Jinja2: started
           Running setup.py install for Jinja2: finished with status 'done'
         Running setup.py install for itsdangerous: started
           Running setup.py install for itsdangerous: finished with status 'done'
         Running setup.py install for Flask: started
           Running setup.py install for Flask: finished with status 'done'
         Running setup.py install for httplib2: started
           Running setup.py install for httplib2: finished with status 'done'
         Found existing installation: six 1.10.0
           Uninstalling six-1.10.0:
             Successfully uninstalled six-1.10.0
         Rolling back uninstall of six
       Exception:
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
           status = self.run(options, args)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
           prefix=options.prefix_path,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
           **kwargs
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
           self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
           isolated=self.isolated,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
           prefix=prefix,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
           d = Distribution(dist_args)
         File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
           _Distribution.__init__(self, attrs)
         File "/app/.heroku/python/lib/python2.7/distutils/dist.py", line 287, in __init__
           self.finalize_options()
         File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
           ep.require(installer=self.fetch_build_egg)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
           items = working_set.resolve(reqs, env, installer, extras=self.extras)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
           new_requirements = dist.requires(req.extras)[::-1]
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires
           dm = self._dep_map
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
           self.__dep_map = self._compute_dependencies()
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
           for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
           metadata = self.get_metadata(self.PKG_INFO)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
           value = self._get(self._fn(self.egg_info, name))
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
           with open(path, 'rb') as stream:
       IOError: [Errno 2] No such file or directory: '/tmp/build_d384526423ee7785219394f160cb0537/twilio-voice-quickstart-server-python-1ed92ad/.heroku/python/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA'
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by bchen-twilio** [comment]
Hi @Jbithell 

Bobie from the SDK team.
We are sorry that you are having trouble using the server sample.

For some reason the `six` library has not happily been working with python for while. I am not expert of the language but I will try if I can find a solution and fix it once and for all.

From the log it seems you already have a newer version (1.10.0) of `six` installed on your machine. Could you try removing the line `six==1.8.0` in the requirements.txt and try `pip install -r requirements.txt` again? I had the similar problem and was able to finish the pip installation after removing that line and just use the originally installed `six` lib.

Thanks.
Please let us know if this helps.

-bobie

**Comment by Jbithell** [comment]
Hi @bchen-twilio,

Thx for the response - unfortunatley it's running on Heroku - so I'm not sure that I can edit requirements.txt - I'll submit a PR. 

James

**Comment by bchen-twilio** [comment]
@Jbithell 

Some of the users might have to deploy to environments without the `six` lib installed.
Could you clone the repository and remove the line in the `requirements.txt` and then deploy to Heroku?

Thanks

**Comment by Jbithell** [comment]
Yes I've tested this on a fork and it works - is there a long term solution for this repo? 

Normally I'd shove in a `xargs -a requirements.txt -n 1 pip install` instead of the normal `install -r` etc. but I don't think this is possible here because of how Heroku works

**Comment by bchen-twilio** [comment]
Hi @Jbithell 

`six` is still a dependency and we need to keep it in case some users are deploying to platforms without it pre-installed. We can definitely do something to the version specifier in the `requirements.txt`.
I'll close this issue since we've resolved it and let's move the discussion to the PR.
Thanks.
